apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: b280awowh-java-quarkus-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/b280awowh-java-quarkus